
import React from 'react';

export const TRANSLATIONS = {
  en: {
    appTitle: 'VM Monitoring System',
    login: 'Login',
    username: 'Username',
    password: 'Password',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot password?',
    dashboard: 'Dashboard',
    vmList: 'VM List',
    history: 'History Data',
    alerts: 'Alert Management',
    users: 'User Management',
    healthScore: 'System Health',
    normalMode: 'Normal Mode',
    faultMode: 'Fault Mode',
    cpu: 'CPU Usage',
    memory: 'Memory Usage',
    disk: 'Disk Usage',
    network: 'Network Traffic',
    activeVMs: 'Active VMs',
    criticalAlerts: 'Critical Alerts',
    viewAll: 'View All',
    troubleshoot: 'Troubleshooting',
    capacityPlanning: 'Capacity Planning',
    editImage: 'AI Image Editor',
    promptPlaceholder: 'Describe edits (e.g., "Highlight high CPU load in red")',
    generating: 'AI is thinking...',
  },
  zh: {
    appTitle: 'VM监控系统',
    login: '登录',
    username: '用户名',
    password: '密码',
    rememberMe: '记住我',
    forgotPassword: '忘记密码？',
    dashboard: '仪表板',
    vmList: 'VM列表',
    history: '历史数据',
    alerts: '告警管理',
    users: '用户管理',
    healthScore: '系统健康评分',
    normalMode: '正常模式',
    faultMode: '故障模式',
    cpu: 'CPU使用率',
    memory: '内存使用率',
    disk: '磁盘使用率',
    network: '网络流量',
    activeVMs: '在线VM',
    criticalAlerts: '严重告警',
    viewAll: '查看全部',
    troubleshoot: '问题排查',
    capacityPlanning: '容量规划',
    editImage: 'AI图像编辑器',
    promptPlaceholder: '描述修改内容（如：“将高CPU负载突出显示为红色”）',
    generating: 'AI正在生成...',
  },
  jp: {
    appTitle: 'VM監視システム',
    login: 'ログイン',
    username: 'ユーザー名',
    password: 'パスワード',
    rememberMe: 'ログイン状態を保持',
    forgotPassword: 'パスワードを忘れた場合',
    dashboard: 'ダッシュボード',
    vmList: 'VM一覧',
    history: '履歴データ',
    alerts: 'アラート管理',
    users: 'ユーザー管理',
    healthScore: 'システム健康スコア',
    normalMode: '通常モード',
    faultMode: '障害モード',
    cpu: 'CPU使用率',
    memory: 'メモリ使用率',
    disk: 'ディスク使用率',
    network: 'ネットワークトラフィック',
    activeVMs: 'アクティブなVM',
    criticalAlerts: '重大なアラート',
    viewAll: 'すべて表示',
    troubleshoot: 'トラブルシューティング',
    capacityPlanning: 'キャパシティプランニング',
    editImage: 'AI画像エディタ',
    promptPlaceholder: '編集内容を入力（例：「高いCPU負荷を赤で強調表示する」）',
    generating: 'AIが生成中...',
  }
};

export const COLORS = {
  bg: '#0f1419',
  card: '#1a1f2e',
  border: '#2a3441',
  success: '#00d4aa',
  warning: '#ff9800',
  danger: '#f44336',
  info: '#2196f3',
  primary: '#4caf50',
};
